/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param description 
 * @param dueDate 
 * @param dueTime 
 * @param isCompleted 
 * @param isReminderEnabled 
 * @param location 
 * @param latitude 
 * @param longitude 
 * @param geofenceRadius 
 * @param createdAt 
 * @param updatedAt 
 */


data class Task (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "dueDate")
    val dueDate: kotlin.Long? = null,

    @Json(name = "dueTime")
    val dueTime: kotlin.Long? = null,

    @Json(name = "isCompleted")
    val isCompleted: kotlin.Boolean? = null,

    @Json(name = "isReminderEnabled")
    val isReminderEnabled: kotlin.Boolean? = null,

    @Json(name = "location")
    val location: kotlin.String? = null,

    @Json(name = "latitude")
    val latitude: kotlin.Double? = null,

    @Json(name = "longitude")
    val longitude: kotlin.Double? = null,

    @Json(name = "geofenceRadius")
    val geofenceRadius: kotlin.Float? = null,

    @Json(name = "createdAt")
    val createdAt: kotlin.Long? = null,

    @Json(name = "updatedAt")
    val updatedAt: kotlin.Long? = null

) {


}

