/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param inputs 
 * @param userId 
 * @param workflowId 
 * @param streaming 
 */


data class WorkflowRequest (

    @Json(name = "inputs")
    val inputs: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "userId")
    val userId: kotlin.String? = null,

    @Json(name = "workflowId")
    val workflowId: kotlin.String? = null,

    @Json(name = "streaming")
    val streaming: kotlin.Boolean? = null

) {


}

