/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param outputs 
 * @param workflowId 
 * @param executionId 
 * @param taskId 
 * @param status 
 * @param errorMessage 
 * @param createdAt 
 * @param finishedAt 
 * @param elapsedTime 
 * @param totalTokens 
 * @param success 
 * @param metadata 
 */


data class WorkflowResponse (

    @Json(name = "outputs")
    val outputs: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "workflowId")
    val workflowId: kotlin.String? = null,

    @Json(name = "executionId")
    val executionId: kotlin.String? = null,

    @Json(name = "taskId")
    val taskId: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "errorMessage")
    val errorMessage: kotlin.String? = null,

    @Json(name = "createdAt")
    val createdAt: kotlin.Long? = null,

    @Json(name = "finishedAt")
    val finishedAt: kotlin.Long? = null,

    @Json(name = "elapsedTime")
    val elapsedTime: kotlin.Long? = null,

    @Json(name = "totalTokens")
    val totalTokens: kotlin.Int? = null,

    @Json(name = "success")
    val success: kotlin.Boolean? = null,

    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

