/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Task

class TaskTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Task
        //val modelInstance = Task()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `dueDate`
        should("test dueDate") {
            // uncomment below to test the property
            //modelInstance.dueDate shouldBe ("TODO")
        }

        // to test the property `dueTime`
        should("test dueTime") {
            // uncomment below to test the property
            //modelInstance.dueTime shouldBe ("TODO")
        }

        // to test the property `isCompleted`
        should("test isCompleted") {
            // uncomment below to test the property
            //modelInstance.isCompleted shouldBe ("TODO")
        }

        // to test the property `isReminderEnabled`
        should("test isReminderEnabled") {
            // uncomment below to test the property
            //modelInstance.isReminderEnabled shouldBe ("TODO")
        }

        // to test the property `location`
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

        // to test the property `latitude`
        should("test latitude") {
            // uncomment below to test the property
            //modelInstance.latitude shouldBe ("TODO")
        }

        // to test the property `longitude`
        should("test longitude") {
            // uncomment below to test the property
            //modelInstance.longitude shouldBe ("TODO")
        }

        // to test the property `geofenceRadius`
        should("test geofenceRadius") {
            // uncomment below to test the property
            //modelInstance.geofenceRadius shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
