/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.WorkflowRequest

class WorkflowRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WorkflowRequest
        //val modelInstance = WorkflowRequest()

        // to test the property `inputs`
        should("test inputs") {
            // uncomment below to test the property
            //modelInstance.inputs shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `workflowId`
        should("test workflowId") {
            // uncomment below to test the property
            //modelInstance.workflowId shouldBe ("TODO")
        }

        // to test the property `streaming`
        should("test streaming") {
            // uncomment below to test the property
            //modelInstance.streaming shouldBe ("TODO")
        }

    }
}
