/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.WorkflowResponse

class WorkflowResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WorkflowResponse
        //val modelInstance = WorkflowResponse()

        // to test the property `outputs`
        should("test outputs") {
            // uncomment below to test the property
            //modelInstance.outputs shouldBe ("TODO")
        }

        // to test the property `workflowId`
        should("test workflowId") {
            // uncomment below to test the property
            //modelInstance.workflowId shouldBe ("TODO")
        }

        // to test the property `executionId`
        should("test executionId") {
            // uncomment below to test the property
            //modelInstance.executionId shouldBe ("TODO")
        }

        // to test the property `taskId`
        should("test taskId") {
            // uncomment below to test the property
            //modelInstance.taskId shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `errorMessage`
        should("test errorMessage") {
            // uncomment below to test the property
            //modelInstance.errorMessage shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `finishedAt`
        should("test finishedAt") {
            // uncomment below to test the property
            //modelInstance.finishedAt shouldBe ("TODO")
        }

        // to test the property `elapsedTime`
        should("test elapsedTime") {
            // uncomment below to test the property
            //modelInstance.elapsedTime shouldBe ("TODO")
        }

        // to test the property `totalTokens`
        should("test totalTokens") {
            // uncomment below to test the property
            //modelInstance.totalTokens shouldBe ("TODO")
        }

        // to test the property `success`
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
