/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.AiControllerApi
import org.openapitools.client.models.WorkflowRequest
import org.openapitools.client.models.WorkflowResponse

class AiControllerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AiControllerApi
        //val apiInstance = AiControllerApi()

        // to test getClientsStatus
        should("test getClientsStatus") {
            // uncomment below to test getClientsStatus
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getClientsStatus()
            //result shouldBe ("TODO")
        }

        // to test getStatus
        should("test getStatus") {
            // uncomment below to test getStatus
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getStatus()
            //result shouldBe ("TODO")
        }

        // to test workflow
        should("test workflow") {
            // uncomment below to test workflow
            //val workflowRequest : WorkflowRequest =  // WorkflowRequest | 
            //val result : WorkflowResponse = apiInstance.workflow(workflowRequest)
            //result shouldBe ("TODO")
        }

        // to test workflowWithClient
        should("test workflowWithClient") {
            // uncomment below to test workflowWithClient
            //val clientType : kotlin.String = clientType_example // kotlin.String | 
            //val workflowRequest : WorkflowRequest =  // WorkflowRequest | 
            //val result : WorkflowResponse = apiInstance.workflowWithClient(clientType, workflowRequest)
            //result shouldBe ("TODO")
        }

    }
}
