/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.TaskControllerApi
import org.openapitools.client.models.Task

class TaskControllerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TaskControllerApi
        //val apiInstance = TaskControllerApi()

        // to test createTask
        should("test createTask") {
            // uncomment below to test createTask
            //val task : Task =  // Task | 
            //val result : Task = apiInstance.createTask(task)
            //result shouldBe ("TODO")
        }

        // to test deleteTask
        should("test deleteTask") {
            // uncomment below to test deleteTask
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : kotlin.Boolean = apiInstance.deleteTask(id)
            //result shouldBe ("TODO")
        }

        // to test disableTaskReminder
        should("test disableTaskReminder") {
            // uncomment below to test disableTaskReminder
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : kotlin.Boolean = apiInstance.disableTaskReminder(id)
            //result shouldBe ("TODO")
        }

        // to test enableTaskReminder
        should("test enableTaskReminder") {
            // uncomment below to test enableTaskReminder
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : kotlin.Boolean = apiInstance.enableTaskReminder(id)
            //result shouldBe ("TODO")
        }

        // to test getAllTasks
        should("test getAllTasks") {
            // uncomment below to test getAllTasks
            //val result : kotlin.collections.List<Task> = apiInstance.getAllTasks()
            //result shouldBe ("TODO")
        }

        // to test getTaskById
        should("test getTaskById") {
            // uncomment below to test getTaskById
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : Task = apiInstance.getTaskById(id)
            //result shouldBe ("TODO")
        }

        // to test getTaskStatistics
        should("test getTaskStatistics") {
            // uncomment below to test getTaskStatistics
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Long> = apiInstance.getTaskStatistics()
            //result shouldBe ("TODO")
        }

        // to test getTasksByCompleted
        should("test getTasksByCompleted") {
            // uncomment below to test getTasksByCompleted
            //val isCompleted : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : kotlin.collections.List<Task> = apiInstance.getTasksByCompleted(isCompleted)
            //result shouldBe ("TODO")
        }

        // to test getTasksByDateRange
        should("test getTasksByDateRange") {
            // uncomment below to test getTasksByDateRange
            //val startDate : kotlin.Long = 789 // kotlin.Long | 
            //val endDate : kotlin.Long = 789 // kotlin.Long | 
            //val result : kotlin.collections.List<Task> = apiInstance.getTasksByDateRange(startDate, endDate)
            //result shouldBe ("TODO")
        }

        // to test getTasksByLocation
        should("test getTasksByLocation") {
            // uncomment below to test getTasksByLocation
            //val latitude : kotlin.Double = 1.2 // kotlin.Double | 
            //val longitude : kotlin.Double = 1.2 // kotlin.Double | 
            //val radius : kotlin.Double = 1.2 // kotlin.Double | 
            //val result : kotlin.collections.List<Task> = apiInstance.getTasksByLocation(latitude, longitude, radius)
            //result shouldBe ("TODO")
        }

        // to test markTaskAsCompleted
        should("test markTaskAsCompleted") {
            // uncomment below to test markTaskAsCompleted
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : kotlin.Boolean = apiInstance.markTaskAsCompleted(id)
            //result shouldBe ("TODO")
        }

        // to test markTaskAsUncompleted
        should("test markTaskAsUncompleted") {
            // uncomment below to test markTaskAsUncompleted
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : kotlin.Boolean = apiInstance.markTaskAsUncompleted(id)
            //result shouldBe ("TODO")
        }

        // to test searchTasksByTitle
        should("test searchTasksByTitle") {
            // uncomment below to test searchTasksByTitle
            //val title : kotlin.String = title_example // kotlin.String | 
            //val result : kotlin.collections.List<Task> = apiInstance.searchTasksByTitle(title)
            //result shouldBe ("TODO")
        }

        // to test toggleTaskCompletion
        should("test toggleTaskCompletion") {
            // uncomment below to test toggleTaskCompletion
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : kotlin.Boolean = apiInstance.toggleTaskCompletion(id)
            //result shouldBe ("TODO")
        }

        // to test updateTask
        should("test updateTask") {
            // uncomment below to test updateTask
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val task : Task =  // Task | 
            //val result : Task = apiInstance.updateTask(id, task)
            //result shouldBe ("TODO")
        }

    }
}
